name: Go

on: [pull_request]

jobs:
  Unit_Test:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Go 1.21
        uses: actions/setup-go@v4
        with:
          go-version: 1.21

      - name: Run Tests
        run: |
          make ci-test-unit

      - name: Test Summary
        if: '!cancelled()'
        uses: robherley/go-test-action@v0.1.0
      