name: Go

on: [pull_request]

jobs:
  Unit_Test:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Go 1.21
        uses: actions/setup-go@v4
        with:
          go-version: 1.21

      - name: Run Tests
        run: |
          make ci-test-unit

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
